# UUIDs defined by Beetle
BEETLE_SERVICE_UUID = 0xBE00

BEETLE_CHARAC_BDADDR_UUID = 0xBE01
BEETLE_DESC_BDADDR_TYPE_UUID = 0xBE02

BEETLE_CHARAC_HANDLE_RANGE_UUID = 0xBE03

BEETLE_CHARAC_CONNECTED_TIME_UUID = 0xBE04
BEETLE_CHARAC_CONNECTED_GATEWAY_UUID = 0xBE05

# BLE address types
LE_PUBLIC_ADDR = 0
LE_PRIVATE_ADDR = 1
